
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vBox1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label1;

	private global::Gtk.Button BJugar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox1 = new global::Gtk.VBox();
		this.vBox1.Name = "vBox1";
		this.vBox1.Spacing = 6;
		// Container child vBox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Mi Primera Aplicación");
		this.hbox4.Add(this.label1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label1]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.BJugar = new global::Gtk.Button();
		this.BJugar.CanFocus = true;
		this.BJugar.Name = "BJugar";
		this.BJugar.UseUnderline = true;
		this.BJugar.Label = global::Mono.Unix.Catalog.GetString("JUGAR");
		this.hbox4.Add(this.BJugar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.BJugar]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vBox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox1[this.hbox4]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.Add(this.vBox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BJugar.Clicked += new global::System.EventHandler(this.OnBJugarClicked);
	}
}
